### PR TITLE
Start an Access Point on first boot to setup wifi  and camera..

### PR DESCRIPTION
**Pull request by gemi254**
Hello ..
I 've modified myConfig.h in order to create an AP and write a json config file to sd card.
Then this config file can be used to setup both wifi and camera..
Also modified camera_index.h to allow editing wifi settings..

When setFPS before prepMjpeg() is called creates an exeption 
setFPS(  String(json["fps"].asString()).toInt() );

Also  controlLamp(lampVal) in loadConfig not working..
Any suggestions?

### CODE REVIEW

**Comment by s60sc** [comment]
I've added an enhancement to convert files to AVI format on FTP upload, so you may want to rebase your pull request.
I will try out your changes tomorrow.

**Comment by gemi254** [comment]
Merged you changes in order to ftp upload an avi file instead of mjpeg
But the avi file uploaded on ftp is not valid and can't be opened..
Maybe a bug..

**Comment by s60sc** [comment]
fixed AVI bug

**Comment by s60sc** [comment]
I would recommend that instead of using the json library to store config data, use the expressif preferences  library which is simpler to use and doesn't  require the user to download a library - I had version 6 installed and needed to downgrade to version 5.

**Comment by gemi254** [comment]
Merged your changes.. 
But i get 
ERROR: AVI conversion failed 
in 
size_t readClientBuf(File &fh, byte* &clientBuf, size_t buffSize)

**Comment by s60sc** [comment]
in app_httpd.cpp you missed
```const char* _STREAM_PART = "Content-Type: image/jpeg\r\nContent-Length: %10u\r\n\r\n";```

**Comment by gemi254** [comment]
in ftp.cpp readLen is 0 and not entering while
size_t readLen,writeLen = 0;
while (readLen>0){

**Comment by s60sc** [comment]
One other miss, in ```ftp.cpp```, change::
  ```while (fh.available()){```
to 
 ```while (readLen) {```
else index not appended

**Comment by gemi254** [comment]
Used the expressif preferences library to store config to nvs instead os sd card
so no external libraries needed..
Also saving sensor settings to nvs..
  sensor_t * s = esp_camera_sensor_get();
Is it an easy way to setup camera sensor with nvs loaded struct in loadConfig()?
Look at
//Todo setup camera with loaded settings

**Comment by s60sc** [comment]
Stuck in a boot loop, although I manually updated wifi & ftp details in myconfig.h. Suggest that if loadConfig() fails it should next try a saveConfig() to initialise nvs and pick up any changes user has made to myconfig.h.

Camera init OK
SD ready in 1-line mode 
SD card type SDHC, Size: 3840MB, Used space: 47MB, Total space: 3832MB
[I][myConfig.h:96] loadConfig(): Loading config..
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: hostName NOT_FOUND
[E][myConfig.h:104] loadConfig(): Setting default hostname 
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_SSID NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_Pass NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_ip NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_gw NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_sn NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_ns1 NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ST_ns2 NOT_FOUND
[E][Preferences.cpp:457] getBytesLength(): nvs_get_blob len fail: motion NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ftp_server NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ftp_port NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ftp_user NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ftp_pass NOT_FOUND
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: ftp_wd NOT_FOUND
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 0 - WIFI_READY
[I][myConfig.h:206] startWifi(): Setting wifi hostname: CAM_2BC40A24
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 14 - AP_STOP
[I][myConfig.h:224] startWifi(): No stored Credentials. Starting Access point.
[I][myConfig.h:180] setWifiAP(): Starting Access point with SSID CAM_2BC40A24
[I][myConfig.h:182] setWifiAP(): Done. Connect to SSID: CAM_2BC40A24 and navigate to http://192.168.4.1
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 15 - AP_STACONNECTED
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

**Comment by s60sc** [comment]
During testing, after an FTP upload the index page cannot be retrieved

**Comment by gemi254** [comment]
Conversion index_ov2640_html to String was the problem of after an FTP upload the index page cannot be retrieved.
Found another way to set page title that solves that.
Also on first boot in no nvs found will save defaults..

**Comment by s60sc** [comment]
Some complications with conflicts, but I believe it is successful

**Pull request merged**
