### PR TITLE
New version 2.2 compile with arduino-esp32 v1.0.6

### PR DESCRIPTION
**Pull request by gemi254**
Hi..
I make some changes and add some extra features

### CODE REVIEW

**Comment by s60sc** [comment]
Thanks, I’ll look at this over the week

Sent from Mail for Windows 10

From: gemi254
Sent: 26 April 2021 17:04
To: s60sc/ESP32-CAM_MJPEG2SD
Cc: Subscribed
Subject: [s60sc/ESP32-CAM_MJPEG2SD] New version 2.1a compile with arduino-esp32 v1.0.6 (#24)

Hi..
I make some changes and add some extra features

You can view, comment on, or merge this pull request online at:
  https://github.com/s60sc/ESP32-CAM_MJPEG2SD/pull/24
Commit Summary
• Updated user interface
• Added Clock settings
• Send local time to browser
• Fixed timezone settings
• Updated
• Updated
• Updated
• Updated
• Load camera settings on startup
• Inline jquery and sync clock if AP
• Report if ntp fails
• Save and load camera settings
• Synchronize clock to browser for AP connection
• Updated
• Synchronize clock to browser clock for AP connection
• Inline jquery and sync clock if AP
• Save and load camera settings
• Report on ntp failure
• Improved select folder playback
• Improved listDirs and added go up link
• Updated
• Updated
• Added footer information
• Added footer
• Added upTime
• Updated
• Updated
• Added timezones
• Ftp upload task with delete after upload
• Updated fields size
• Url emcoded requests to handle spaces
• ftp upload move
• Updated
• Updated
• Fixed url encoding
• Fixed url encoding
• Merge branch 'master' of https://github.com/s60sc/ESP32-CAM_MJPEG2SD
• Fixed
• Fixed not compiling without 1Wire
• Fix not compiling without 1Wire
• Withour library compiliging
• Fixed compiling
• Update README.md
• Added futurer format card button
• Delete olders files if card is near to full
• Updated
• Delete oldest directory on card full
• Compiled binary for OTA!
• Merge branch 'master' of https://github.com/gemi254/ESP32-CAM_MJPEG2SD
• Updated
• Updated
• Added a format card button
• Compiling without One wire lib
• Delete olders files if card is near to full
• Delete olders files if card is near to full
• Delete oldest directory on card full
• Display version on page header
• Updated
• Display version information
• Updated
• Check station connection and reconnect
• Updated
• Check internet connection and reconnect on power loss
• Added mdns name services
• Compiled binary for OTA v 1.7.4
• Check internet connection and reconnect on power loss
• Merge https://github.com/s60sc/ESP32-CAM_MJPEG2SD
• Increase recording frame rate
• Increase recording frame rate
• Compiled binary for OTA v 1.8
• Merge https://github.com/s60sc/ESP32-CAM_MJPEG2SD
• Compiled binary for OTA v 1.8
• Delete or ftp upload and delete oldest folder
• Fixed save and restore camera settings
• Compiled binary for OTA v 1.8b
• Check if file exists on folder upload and ignore
• Reload on reboot
• New version 1.8b
• Updated
• Updated
• Updated
• Added help title on controls
• Automatic ftp upload on motion detection
• New version 1.8c
• Compiled binary for OTA v 1.8c
• Automatic upload on motion switch
• Create sheduled upload task
• Fixed load/save params
• updated
• Updated
• Added help title on controls
• Compiled binary for OTA ver 1.8c
• Fixed load/save params
• Ver 1.8c
• Updated
• Fixed load/save params, reboot
• New version 1.9
• Compiled binary for OTA ver 1.9
• Updated
• Added remote log button
• Telnet remote debug button
• Automatic ftp upload on motion detection
• Updated ver 1.9
• Remote debug
• memory optimisation and increase recording fps
• Moved some functions on utils.cpp
• Wifi, logging functions
• Enable remote logging
• updated
• updated
• updated
• New features
• New features
• New features
• New features
• Updated
• Remote debug, optimizations
• New version 2.1a,arduino-esp32 v1.0.6
• Compiled binary for OTA ver 2.1a
• Updated
File Changes
• M ESP32-CAM_MJPEG2SD.ino (43) 
• A ESP32-CAM_MJPEG2SD.ino.esp32.bin (0) 
• M README.md (224) 
• M app_httpd.cpp (1082) 
• M camera_index.h (47) 
• M ds18b20.cpp (163) 
• M extras/screenshot.png (0) 
• M ftp.cpp (799) 
• A history.txt (16) 
• M mjpeg2sd.cpp (421) 
• M motionDetect.cpp (9) 
• M myConfig.h (173) 
• A remote_log.h (44) 
• A utils.cpp (362) 
Patch Links:
• https://github.com/s60sc/ESP32-CAM_MJPEG2SD/pull/24.patch
• https://github.com/s60sc/ESP32-CAM_MJPEG2SD/pull/24.diff

**Comment by s60sc** [comment]
Hi

Tried out the logging, SD ok but with telnet got:
Enabling remote log..
V (19:16:12.052) utils: Initialize telnet remote log
E (19:16:12.055) utils: Failed to create socket, fd value: -1

I wrote my own logging function but didn’t publish it. I used a low priority task to write to a cyclic ram buffer (could use psram for bigger buffer). Low priority so doesn’t clash with camera recording/streaming

**Comment by gemi254** [comment]
Hi
You must press the remote log button on camera and within 30 seconds type: telnet [camera_ip] 443 on the remote host..Then the connection will be established and you will see debug log on telnet..
You can also 
set remote_log_mode (line 39) on file utils.cpp to 1 to enable log to a sdcard file that you can view
with view-source:http://[camera ip]/file?log.txt..

if you see function 
int vprintf_into_spiffs_sync it has a WRITE_CACHE_CYCLE = 5 that do write to the ram buffer and every 5 lines
sync to file..

**Comment by s60sc** [comment]
Thanks, telnet working now. 
Maybe you could add a web page dropdown to select log mode dynamically

**Comment by gemi254** [comment]
Ok..
Changed some files ..
Select debug mode dynamically from UI
Maybe need save debug mode in prefs so be able to debug wifi connection on startup..

**Comment by s60sc** [comment]
enhancements added with tweaks and fixes

**Pull request closed without merging**
