### PR TITLE
Cleaning SD card automatically once it's memory is almost full

### PR DESCRIPTION
**Pull request by Ab-Tx**
This function will check if the SD card memory is almost full every hour.

If the SD card has less than a specified ammount of free memory (defined by user, by default it is 200MB) this function will gather all folder names, sort them, and start deleting the oldest recordings until a certain ammount of memory (defined by user, by default it is 1024MB) is cleaned. Empty folders will also be deleted.

This function will only work with folders wich only contain any of the following characters on their name "/1234567890".

### CODE REVIEW

**Comment by s60sc** [comment]
Thanks, I'll look at this tomorrow

**Comment by s60sc** [comment]
To avoid resource contention and blocking, it may be better to use a timer interrupt (timer2 is free) than the loop, the timer ISR wakes a task which calls checkSDcard()

**Comment by s60sc** [comment]
On further thought there is not much going on in the loop task anyway so can leave as is

**Comment by Ab-Tx** [comment]
It would be nice to use a timer interrupt indeed, I'd like to implement it but the only way I know how to do it would be using the Arduino IDE functions. 
I am not familiar with the ESP32 task system yet.

**Comment by Ab-Tx** [comment]
What would you say about creating a low priority task that, as you mentioned, calls the checkSDcard() but instead of using the timer to call the function we used vTaskDelay() to delay each call of the checkSDcard() function? 

I'm suggesting this because ESP32 only has 4 timers (I'm unaware of how many are in use) in total if I ain't mistaken, and this functionality isn't much time sensitive.

**Comment by s60sc** [comment]
Using a delay in the task instead of a timer is a good idea. You can just use arduino delay().
To make best use of esp32 it is a good idea to learn about tasks. The arduino loop() is a priority 1 task in its own right. You don't need to change your current code, the task is just a wrapper.
xTaskCreate(...) In setup, defines and starts task
void SDtask(void* parameter) {  while(true) {     delay(...);     checkSDcard(...);  }}
Sent from Yahoo Mail on Android 
 
  On Sun, 18 Oct 2020 at 15:11, Ab-Tx<notifications@github.com> wrote:   


What would you say about creating a low priority task that, as you mentioned, calls the checkSDcard() but instead of using the timer to call the function we used vTaskDelay() to delay each call of the checkSDcard() function?

I'm suggesting this because ESP32 only has 4 timers (I'm unaware of how many are in use) in total if I ain't mistaken, and this functionality isn't much time sensitive.

**Comment by gemi254** [comment]
> This function will check if the SD card memory is almost full every hour.
> 
> If the SD card has less than a specified ammount of free memory (defined by user, by default it is 200MB) this function will gather all folder names, sort them, and start deleting the oldest recordings until a certain ammount of memory (defined by user, by default it is 1024MB) is cleaned. Empty folders will also be deleted.
> 
> This function will only work with folders wich only contain any of the following characters on their name "/1234567890".

Using an alternative method of checking for card full is to check when a write command ends on function closeMjpeg
and "delete" or "ftp move" the oldest directory when card space is lower than minCardFreeSpace
see my fork ,,, https://github.com/gemi254/ESP32-CAM_MJPEG2SD

**Comment by Ab-Tx** [comment]
> > This function will check if the SD card memory is almost full every hour.
> > If the SD card has less than a specified ammount of free memory (defined by user, by default it is 200MB) this function will gather all folder names, sort them, and start deleting the oldest recordings until a certain ammount of memory (defined by user, by default it is 1024MB) is cleaned. Empty folders will also be deleted.
> > This function will only work with folders wich only contain any of the following characters on their name "/1234567890".
> 
> Using an alternative method of checking for card full is to check when a write command ends on function closeMjpeg
> and "delete" or "ftp move" the oldest directory when card space is lower than minCardFreeSpace
> see my fork ,,, https://github.com/gemi254/ESP32-CAM_MJPEG2SD

Thanks a lot, the method you created looks more compact and better suited for the task.
I assume you already tested it. 
Please open a pull request of your fork, I'll close this one right away.

**Pull request closed without merging**
