### PR TITLE
Update MJPEG2SD.htm

### PR DESCRIPTION
**Pull request by rjsachse**
Added Australian Time Zones

### CODE REVIEW

**Comment by s60sc** [comment]
dont want to add more default time zones as dropdown gets too big

**Comment by rjsachse** [comment]
The issue is daylight savings. All good. I just have to keep adding it in. I personally don't see the issue having a large drop down list. Daylight savings is about to end and all times will be out.

**Comment by s60sc** [comment]
timezone strings are designed to handle daylight savings

**Comment by rjsachse** [comment]
I do understand that, that is why I done this pull, so australian times are always correct with daylight savings time throughout the year. Making it user friendly. Right now Adelaide Australia is GMT+10.30 and aftwr next sunday will be GMT+9.30. Adding this pull will make sure times are always correct if daylight savings or not.

Time zones don't adjust to daylight savings times. Eg this Adelaide string 
ACST-9:30ACDT,M10.1.0,M4.1.0/3  easier to select from drop down than finding and writing this strings or others with daylight savings 

So Adelaide is in 2 different timezones depending on the time of year.

**Pull request closed without merging**
