### PR TITLE
Auto update info bar, Fix & upgrade sdcard log file

### PR DESCRIPTION
**Pull request by gemi254**
Hi..
I've made some bug fixes and adittions

* Auto update information bar on the bottom of the page with get requests. User interface uses a timer to make requests to esp-cam so the bottom bar (uptime,rssi,mem) to be automatically updated every 5 secs.

* Fix bug to log to sdcard file and now works ok. The log file is not deleted and i've added some controls to the log page to reset the log file (delete). Added other options as an auto update link (refresh) and a page move top/bottom link.

Telnet seems to not working at all?

Thanks

### CODE REVIEW

**Comment by s60sc** [comment]
Thanks.
I'm currently reworking some of the code that will be ready in about a week. I'll incorporate your changes.
Telnet works for me - what error are you seeing.

**Comment by gemi254** [comment]
telnet: Unable to connect to remote host: Connection refused
I will check it from another host..

**Comment by s60sc** [comment]
DOH!
Sorry about this.
I uploaded an incorrect version of app_httpd.cpp which prevents telnet connection.
Uploading fix

**Comment by gemi254** [comment]
If logMode is telnet and is saved then on restart the remote_log_init(); will called before  wifi connection
and system reboots infinitive due to an exception...
You must change these lines on utils cpp.
304 -  remote_log_init();                                                  
304 +  //Init remote log
305 +  if(!(logMode == 2 && WiFi.status() != WL_CONNECTED))   remote_log_init();
306 +  else logMode = 0;

Uploading fix

**Pull request merged**
