### PR TITLE
Upload file or folder by ftp to remote server

### PR DESCRIPTION
**Pull request by gemi254**
Upload a folder or file to a remote ftp server.
Day directory will be auto created on remote server
Tested with raspberry pi and pure-ftpd.
A cron job maybe needed to do the job in midnight

### CODE REVIEW

**Comment by s60sc** [comment]
I've tried your FTP upload successfully.

Some suggestions:
- as the ftp function is called from app_httpd.cpp it blocks all activity until it finishes, so it should be run in its own task.
- uploading a folder will be significantly faster if all files are uploaded in the same connection rather than redoing it for each file in the folder
- uploading a file will be faster if the ftp buffer size is the same as the SD card cluster size. May need to ps_malloc it.

**Comment by gemi254** [comment]
Hello...
Thank you for your suggestions..
I've made some changes.. 
* Updated the ftp.cpp so multiple directory files will stored without disconnection.
* Created a task for uploading the files so app_httpd.cpp will be still functional during upload proccess..
* I 've also used ps_malloc for the ftp buffer to be a little bit larger but i think that has no effect
since the ftp dclient.write is mutch slower tha sd read..
Also noticed that with small ftp buffer size multitasking is more smooth..

**Comment by s60sc** [comment]
Successfully tested improvements.

ftp dclient.write depends on connection speed, ftp server etc and can be much faster than SD read

to speed up SD read, instead of reading one byte at a time into the buffer
```clientBuf[clientCount] = fh.read();```
read a 32k cluster into the buffer 
```size_t readLen = fh.read(clientBuf, CLUSTERSIZE);```

**Comment by gemi254** [comment]
Successfully done you suggested improvements.
Now reads 32k buffer size and write it to ftp
Works much more faster now..

**Comment by s60sc** [comment]
Merge completed.

> Is there a way to do this inside esp32 with sd_mmc library?

Could try this:
[https://www.esp32.com/viewtopic.php?t=10348](https://www.esp32.com/viewtopic.php?t=10348)

**Pull request merged**
